### ISSUE TITLE
ImportError: No JS module 'data' found in search path

### ISSUE THREAD

**Issue by devhammed** [maoschanz/emoji-selector-for-gnome#100]
I am started getting this error after updating to the latest version on Ubuntu 20.04.

**Comment by sp1ritCS** [comment]
Same for me, Arch (k5.6.7), GNOME Shell 3.36.1

I think the issue is just with the newest version of the plugin, you could try reverting back a version and if that works.

**Comment by maoschanz** [comment]
ooooh fuck the data directory hasn't been added to the zip

sorry, that's a very stupid error

**Comment by maoschanz** [comment]
no idea when the version 18 will be approved, meanwhile i've removed the version 17 from the website: you can reinstall it to get the version 16 or wait a few days

**Comment by devhammed** [comment]
Okay, thank you.

**Comment by maoschanz** [comment]
(i let it open just so other people with the problem could see it)

**Comment by maoschanz** [comment]
> no idea when the version 18 will be approved

now it is, i hope it works

**Comment by devhammed** [comment]
I have installed the new update and it is working again! 🎉🎉🎉

PS: I used the emoji from the extension!
