### ISSUE TITLE
Not working anymore after latest update on EGO

### ISSUE THREAD

**Issue by amivaleo** [maoschanz/emoji-selector-for-gnome#104]
Hi,

After latest update from the gnome extension website, this extension doesn't work anymore. I get an "Error" button on the website and nothing new appears in my gnome top-panel.

I checked in the metadata.json file. The version that I have now is 16.

I also checked in looking-glass and it says "TypeError: Extension.SETTINGS is undefined".

I use Fedora 31, gnome-shell 3.34.5.

I see there's a new version of this extension in the review queue in EGO ( https://extensions.gnome.org/review/16237 ), which is labelled as version 18. I hope that it will fix the issue. I'll close this report if that's the case.

**Comment by amivaleo** [comment]
After a reboot, it works fine...

I... I just don't understand computers maybe.

**Comment by maoschanz** [comment]
No, GNOME Shell is just getting clever: it tried to update to version 17, and when it failed it decided to keep version 16. It will not retry (the version 17 is supposed to be inactivated on EGO, precisely because it fails, see #100)

But the main point of version 17 (18 now) is compatibility with GS 3.36 so it will not fix many issues for you anyway lol

(and I hope the version 19 will be the one with your PR!)

**Comment by amivaleo** [comment]
Yeah, I saw that 17 is inactive indeed.

I've just updated my computer to fedora 32. Now I have gnome-shell 3.36. I still have to settle down a bit and make a few things work again after they got a bit broken.

If anything seems broken in your extension too, I'll try to help by some (hopefully) clever reporting here.

No worries for the PR. It might be even quite old now or not that useful as I thought when I made it.

**Comment by maoschanz** [comment]
the categories you did make more sense than the current ones, and you added quite a lot of emojis, the only big issue was that the information about compatibility with skin color or other modifiers has been lost. But that feature is more and more broken (now there are "red hair", "bald", "curly hair", etc. the current code can't do that, it has to change)
