### ISSUE TITLE
Emoji Categories Hard to Read

### ISSUE THREAD

**Issue by thejustinwalsh** [maoschanz/emoji-selector-for-gnome#111]
![image](https://user-images.githubusercontent.com/72912/81028866-f2701a80-8e37-11ea-948d-9cda4d22c1cf.png)

Ubuntu 20.04 Default Shell Theme.
Looks great in Yaru-Dark though!

**Comment by maoschanz** [comment]
#107

**Comment by thejustinwalsh** [comment]
I searched too, apparently not that hard though. Thanks!

**Comment by yanike** [comment]
This is still an issue. Please fix the extension.
