### ISSUE TITLE
No-contrast light icons when on light shell theme

### ISSUE THREAD

**Issue by bkis** [maoschanz/emoji-selector-for-gnome#113]
I'm on Pop!_OS 20.04 (if that's relevant) using the light theme. The extension uses bright icons for the buttons - they're barely visible. All other extensions pick up the theme type just fine, so I suspect it's an issue in this extension:

![image](https://user-images.githubusercontent.com/9215743/81808253-bc115a00-951f-11ea-90c0-e2da7ae9b254.png)

**Comment by bkis** [comment]
Sorry I didn't find any open related issues. But I admittedly only had a very superficial scan through the list...

**Comment by maoschanz** [comment]
you didn't view them because they're closed, the new version of the extension is [here, still waiting](https://extensions.gnome.org/review/)
