### ISSUE TITLE
Symbols and Flags categories don't load at all

### ISSUE THREAD

**Issue by nicolasmaia** [maoschanz/emoji-selector-for-gnome#114]
Maybe because there are too many, but those categories don't load. The app doesn't crash, though. When I click on the other categories, results are normal.

**Comment by maoschanz** [comment]
1. version of the extension?
2. version of GNOME Shell?
3. since there was an update less than an hour ago, what if you close and reopen your session?

**Comment by nicolasmaia** [comment]
1. v19 (I updated it this morning)
2. 3.30.2
3. Gonna try that in a sec, brb

**Comment by nicolasmaia** [comment]
1. v19 (I updated it this morning)
2. 3.30.2
3. Gonna try that in a sec, brb
