### ISSUE TITLE
Application doesn't opens in Ubuntu 20.04

### ISSUE THREAD

**Issue by adarshaacharya** [maoschanz/emoji-selector-for-gnome#122]
I copied **emoji-selector@maestroschan.fr** folder into my `/usr/share/gnome-shell/extensions` folder
but when i tried to lauch app using Super key + E then it won't launch. I tried checking shortcuts from Settings but can't find **Super key + E.**

I can manually add shortcut but what is the command to lauch for the application.

![image](https://user-images.githubusercontent.com/50266088/86274063-d814ac00-bbf0-11ea-98ff-e87e5773c3b4.png)

**Comment by maoschanz** [comment]
it's not an application, there is no command

if you want to add a shortcut, you have to use the provided settings window. Just chose a shortcut that isn't already used by the desktop environment (`<Super>n` by default sets the focus on the active notification, if you want to use it for emojis you have to unset it from this feature before trying to use it for something else)
