### ISSUE TITLE
😅 is being copied as 😄

### ISSUE THREAD

**Issue by BenBergman** [maoschanz/emoji-selector-for-gnome#125]
Clicking on 😅 in the selector puts 😄 in the clipboard.

**Comment by maoschanz** [comment]
i can't reproduce your issue at all, both emojis are correctly copied when i click on them

**Comment by BenBergman** [comment]
My computer crashed overnight and this morning on a fresh boot it is working again.

I swear yesterday I tested it a dozen times before submitting this report. Oh well, thanks for trying on your end.
