### ISSUE TITLE
Keyboard shortcut not displaying the selector in the primary display

### ISSUE THREAD

**Issue by bernardogarza** [maoschanz/emoji-selector-for-gnome#126]
When I use the keyboard shortcut it opens the selector in my secondary display. I'm using a laptop and have an external monitor connected through DisplayPort, in Ubuntu my primary display is the external one and when I use the keyboard shortcut It opens in the laptop display. I'm using the `Dash to Panel` extension, and I'm only displaying my panel on my primary display.

**Comment by maoschanz** [comment]
can you post a screenshot?

and, if possible, install something like Clipboard Indicator and tell me if its keyboard shortcut works the same way?

**Comment by bernardogarza** [comment]
I found out that the bug only happens when 'Panel Intellihide' is on. It must be a conflict between the dash to panel extension and this one.

Thanks!
