### ISSUE TITLE
Cannot bind `<Super>.` or `<Super>;` as keyboard shortcut toggle

### ISSUE THREAD

**Issue by viktorpenelski** [maoschanz/emoji-selector-for-gnome#128]
Cannot bind `<Super>.` or `<Super>;` as keyboard shortcut via the settings menu.

![image](https://user-images.githubusercontent.com/9766351/92109732-3842ec80-edf2-11ea-8cb8-a4512822176c.png)

Expected behavior: When the shortcut is `<Super>.`, the emoji menu should toggle when holding the "Super" key and pressing `.`.
Actual behavior: With the above configuration in place, no interaction with the extension occurs.

Other binds seem to be working as expected - for example, there are no issues when `<Super>l` is configured.

---

Version: (v19)
OS: Ubuntu 20.04 LTS
GNOME: 3.36.1

**Comment by maoschanz** [comment]
https://raw.githubusercontent.com/GNOME/gtk/master/gdk/keynames.txt

`<Super>period` probably

**Comment by viktorpenelski** [comment]
`<Super>period` works perfectly!

@maoschanz - thank you so much! 🙏
That response was unbelievably fast, despite the nooby question.

**Comment by maoschanz** [comment]
you're not the first one to ask (#50, #53, ...), so i already knew the answer

i've even decided to put the link i just gave you directly in the app but it's not released yet

![Capture d’écran de 2020-09-03 14-04-03](https://user-images.githubusercontent.com/19996113/92112611-59094300-edee-11ea-938a-e67d5ebfc4db.png)
