### ISSUE TITLE
Gnome 3.38 error

### ISSUE THREAD

**Issue by MrMelon54** [maoschanz/emoji-selector-for-gnome#133]
In the gnome 3.38 this extension gives the error `meta is null`

**Comment by maoschanz** [comment]
i should create a label to put on every issue where the reporter did great efforts to find the text message of the actual error, but didn't do the effort to check if the extension was even supposed to support GNOME 3.38 in the first place

**Comment by MrMelon54** [comment]
I know it doesn't have 3.38 in the download list on the gnome extensions site but I still wanted to point out that it didn't work

**Comment by maoschanz** [comment]
the code which isn't supposed to work indeed doesn't work. But the code in this git repo does work, since the 6 days old commit i referenced.

Then i've no control over the date of the release

**Comment by yob** [comment]
Thanks for the quick fix!

Unfortunately I didn't notice the list of supported Gnome versions - here's what I see on https://extensions.gnome.org/ after my debian system upgraded to 3.38:

![Screenshot from 2020-10-05 20-00-39](https://user-images.githubusercontent.com/8132/95060121-92163980-0745-11eb-93b8-f9a60960ca90.png)

> Then i've no control over the date of the release (extensions need to be reviewed before you get the update)

this sounds promising - so a new version has been uploaded to the extensions site and we're just waiting for the review process to do its thing?

**Comment by maoschanz** [comment]
the list of compatible versions is in the details page, here: 
![image](https://user-images.githubusercontent.com/19996113/95061251-a46b8580-06fb-11eb-9713-8a6175c1b614.png)

they should change the website to make it more obvious, people installing incompatible extensions is such a recurring issue

**Comment by AlexWayfer** [comment]
> but didn't do the effort to check if the extension was even supposed to support GNOME 3.3[x] in the first place

I think such issues are more like "please, add support for GNOME 3.x", not like "this extension *must* works in the GNOME 3.x, fix it!".

**Comment by maoschanz** [comment]
It's semantic, but you look at the wrong period: there are no breakage between 3.36.0 and 3.36.4 for example.

Anyway, i've added an issue template, people should understand the situation while they fill it
