### ISSUE TITLE
Not working after update to Gnome 3.38

### ISSUE THREAD

**Issue by DestroyerXyz** [maoschanz/emoji-selector-for-gnome#136]
# System

- OS: Arch Linux
- Your version of the extension (visible in the "about" tab of the preferences window): Latest
- Your version of GNOME Shell: 3.38
- Most recent GNOME Shell version that is supposed to work ([visible here](https://extensions.gnome.org/extension/1162/emoji-selector/) in the dropdown): 3.36
- Is the extension supposed to work with your version of GNOME Shell [y/n]: n

# Description of the bug

Is your bug already reported? [y/n]: n

## To Reproduce

Steps to reproduce the bug:

1. ...
2. ...
3. ...

**Comment by maoschanz** [comment]
>Is your bug already reported? [y/n]: n

It is. Several times.

>Is the extension supposed to work with your version of GNOME Shell [y/n]: n

So, what's your conclusion?

**Comment by nils-werner** [comment]
Duplicate of #133

**Comment by skewty** [comment]
This issue is closed and the latest comment on extensions.gnome.org says this is working in MASTER.  
I see no new Tags and the version on extensions.gnome.org does not mention 3.38 compatibility.
Am I missing something?  Should this issue not be left open for all to easily find until the download on extensions.gnome.org has been updated or there is a comment saying will not fix?

**Comment by maoschanz** [comment]
you're missing that 3.28 users aren't less important than 3.38 users, so i have to test on a VM for the retro-compatibility with Ubuntu 18.04 before releasing the new version.

and it takes time and patience to install a VM with an old GNOME Shell on a cheap laptop. You can test it if you have more than me.

Things to test are:

- does the keybinding work
- does the preferences dialog work
- type something in the search (most tiles must become blank), erase the searched text, and check if the last emoji of the recently used list can be clicked
- put many emojis per line, restart, and check if the buttons for categories are evenly spaced
- does typing "gun" find the gun emoji

**Comment by skewty** [comment]
Would detecting the Gnome-Shell version and branching be a better long-term approach?

https://stackoverflow.com/questions/34120963/how-can-my-gnome-shell-extension-detect-the-gnome-version

If you are open to a solution with Gnome-Shell version detection to future proof the extension then I would be willing to assist and help refactor the code, where required, to better handle various versions without branching.  I haven't looked at the source code yet, but I'd guess that some dependency injection / composition would work for this.

**Comment by maoschanz** [comment]
>I haven't looked at the source code yet

you may want to first look at this part https://github.com/maoschanz/emoji-selector-for-gnome/blob/8705be224a762fd750a9b420cc68a2271b2cb025/emoji-selector%40maestroschan.fr/extension.js#L43

>where required

to know where it's required, the code has to be tested with 3.28, to know if the various new fixes and features work

**Comment by skewty** [comment]
> Things to test are:
>     * does the keybinding work
>     * does the preferences dialog work
>     * type something in the search (most tiles must become blank), erase the searched text, and check if the rightmost emoji of the recently used list can be clicked
>     * put many emojis per line, restart, and check if the buttons for categories are evenly spaced
>     * does typing "gun" find the gun emoji

#### Results using fresh git clone of master with fresh install of Ubuntu 18.04 on a VM:
- keybinding works
- preferences works
- text search works
- gun 🔫 search works

 >     * put many emojis per line, restart, and check if the buttons for categories are evenly spaced

I didn't really understand this one so I didn't do this test

**Comment by maoschanz** [comment]
>I didn't really understand this one so I didn't do this test

the default value is 12 emojis per line which is enough to see the issue, so i assume if it was broken you would have noticed the ugliness

it's released, now the changes have to be reviewed and this delay isn't something i control

**Comment by maoschanz** [comment]
it was quick this time
