### ISSUE TITLE
Latest update breaks on Ubuntu 20.04

### ISSUE THREAD

**Issue by BloodyIron** [maoschanz/emoji-selector-for-gnome#139]
Not sure where to check for logs, but I'm on Ubuntu 20.04, and saw there was an update for this extension. It was working before the update, updated as of this writing, and now it won't start.

**Comment by maoschanz** [comment]
![image](https://user-images.githubusercontent.com/19996113/97118741-2142bb80-170c-11eb-948e-fd6f59e12fff.png)

**Comment by maoschanz** [comment]
I've tested on the machine at my work, which is kinda Ubuntu 20.04, and as i expected it works fine after restarting GNOME Shell, so i'll close this issue

If it still doesn't work on your machine, please provide the result of the command `sudo journalctl -a /usr/bin/gnome-shell | grep "emoji"`

**Comment by BloodyIron** [comment]
So I really don't appreciate your first response here, quite rude frankly. But the logs you pointed me to shows that I need to log out and back in for this extension to take effect. Why, I don't know, but that's the error it's throwing so II will try that next.

And yes, I tried turning all of the extensions off and on again if you absolutely must ask that tired question.

**Comment by maoschanz** [comment]
>quite rude frankly

come on it's a meme

this is not professional support this is a personal project i share on the internet

>And yes, I tried turning all of the extensions off and on again if you absolutely must ask that tired question.

Extensions are patches applied to the running gnome-shell process, so it's not about turning the extension on and off, it's about turning Gnome Shell on and off (like the message you found recommends). IIRC clicking on the switch to turn it on and off during an update will try to run code from the version that isn't installed anymore.

i've no idea how you did the update, but when i do it from the "Extensions" app, it tells me explicitly that i have to log out to apply anything

**Comment by BloodyIron** [comment]
Well, it may have been intended to be a jovial meme image, that is not the original impression that I received :P

I was unaware that toggling the switch would trigger it to run the old code, that's really weird as other extension upgrades I've done in the past seem to have not shown the same behaviour (for all I know they could have used the old code until I rebooted/relogged without me knowing). In that they "just worked" (most of the time).

Whenever I get notifications for updates to extensions I use, I go to the gnome extension website and update through the browser plugin method. Thus-far I do not recall being told to log out/back in to apply updates for any extension update, so not sure what's up with that.
