### ISSUE TITLE
Slow start of Gnome Shell 

### ISSUE THREAD

**Issue by xzj8b3** [maoschanz/emoji-selector-for-gnome#142]
the extension slows down Gnome-Shell startup going a bit in conflict with extensions like "Floating Dock" on Fedora 33 with Gnome Shell 3.38.1, it should be optimized a bit!

**Comment by maoschanz** [comment]
This extension is already quite optimized: to be sure it doesn't slow down anything at startup, it doesn't even load the emojis until you click to open the submenus with categories of emojis...

Then once loaded it may sucks regarding memory footprint, but it's an other problem

----

Sorry but unless you have clues that my code is actually involved, it's not really my concern if "Floating Dock" has performance issues
