### ISSUE TITLE
Have ability to set extension icon position and order

### ISSUE THREAD

**Issue by r3b311i0n** [maoschanz/emoji-selector-for-gnome#143]
I think it would be a good enhancement to have the ability to set the position and the order of the extension icon. Right now I'm editing `extension.js` and changing  the values in `addToStatusArea` manually. The [arch-update extension](https://github.com/RaphaelRochet/arch-update) has this built into its settings.

![Screenshot from 2020-11-24 21-04-14](https://user-images.githubusercontent.com/10097295/100115515-9f73b880-2e98-11eb-8b6a-1a99ae02c0b3.png)

**Comment by maoschanz** [comment]
what's the point

**Comment by r3b311i0n** [comment]
To easily control where the extension icon appears on the top bar. When the system starts, the app indicator icons are on the far left on my system. The emoji selector icon is right next to it. But sometimes after a while, I've noticed that they swap positions. Restarting the shell resets them to their original positions. It's just a bit annoying to me.

**Comment by AlexWayfer** [comment]
To move your mouse less every time. I guess, people often use emoji selector and rarer something like applications icons (tray), system graphs, etc.

**Comment by maoschanz** [comment]
>To move your mouse less every time

the keyboard workflow might be broken when it comes to browsing a category, but opening the menu and searching works fine

>To easily control where the extension icon appears on the top bar.

Something "a bit annoying" (probably related to appindicators that keep stopping and restarting?) isn't worth adding the code for yet another option in the first place, but here it's not even really a feature of the extension: it looks like you're looking for a "top panel organizer" extension. Changing the relative index of an indicator only makes sense if you can change all of them, and you'll never make every extension out there add those options.
