### ISSUE TITLE
how to open the setting dialog?

### ISSUE THREAD

**Issue by todatamining** [maoschanz/emoji-selector-for-gnome#146]
# System

- OS: 
ubuntu18.04

- Your version of the extension (visible in the "about" tab of the preferences window):
I don't know. There is no about menu in this extension. There is emoji selection menu. 
But I think its the latest version of 12/29/2020, because I clone the git repo.

- Your version of GNOME Shell: 
GNOME Shell 3.28.4

# Description of the bug

Is your bug already reported? [y/n]:
there is a bug "Setting dialog does not load #101", which is an old version. 
I searched prefs.js and I can't find "always-show-label" in this js.
I am using the latest code download from git and install it manually.

## To Reproduce

Steps to reproduce the bug:

1. git clone https://github.com/maoschanz/emoji-selector-for-gnome.git or select "download ZIP"
2. go the cloned repo or extract the ZIP, then open a terminal in the project's directory, and run ./install.sh
3. restart the GNOME Shell environment 
4. I didn't see the setting dialog, and there is no option to open it.

## Expected behavior
open the setting dialog automatically or there is a way to open the setting dialog

**Comment by maoschanz** [comment]
it works like with any other existing extension... How do you manage them?

- if you use the web interface, there is an "options" button next to the name of the extension
- ~~if you use `gnome-extensions-app`, there is an "options" button next to the name of the extension
- if you use the native `gnome-shell-extension-prefs`, there is an "options" button next to the name of the extension
- if you use `gnome-tweaks`, there is an "options" button next to the name of the extension

**Comment by todatamining** [comment]
Thanks a lot for looking into this issue! I tried gnome-shell-extension-prefs, and I can change the setting now :+1:

**Comment by todatamining** [comment]
Thanks a lot for looking into this issue!
I am not familiar with gnome-extensions. Maybe emoji-selector-for-gnome is the only gnome-extension I have :)
I tried gnome-shell-extension-prefs, and I can change the setting now +1

**Comment by todatamining** [comment]
Thanks a lot for looking into this issue!
I am not familiar with gnome-extensions.  emoji-selector-for-gnome is the only gnome-extension I have ever used.
I tried gnome-shell-extension-prefs, and I can change the setting now :+1:
