### ISSUE TITLE
Picking and Pasting Gives Different Emoji

### ISSUE THREAD

**Issue by psycotica0** [maoschanz/emoji-selector-for-gnome#153]
# System

- OS: Ubuntu 20.04
- Your version of the extension (visible in the "about" tab of the preferences window): v20
- Your version of GNOME Shell: 3.36.7
- Most recent GNOME Shell version that is supposed to work ([visible here](https://extensions.gnome.org/extension/1162/emoji-selector/) in the dropdown): 3.38
- Is the extension supposed to work with your version of GNOME Shell [y/n]: y

# Description of the bug

Is your bug already reported? [y/n]: n

(But might be related to https://github.com/maoschanz/emoji-selector-for-gnome/issues/125)

Ok, this will likely not be reproducible, but the issue I'm having is that when I search for emoji I get ones that seem weird given the search result, but when I pick them they're the right emojis, just not the ones it showed.

I tried disabling and re-enabling the extension but that doesn't seem to have fixed it. I haven't tried removing it completely and reinstalling it, or restarting my computer, any of which may help. I wanted to report this because it's super weird, and maybe there's some way this makes sense to you that could explain what I'm seeing...

![emoji picker weird](https://user-images.githubusercontent.com/12766/121199232-c431eb00-c840-11eb-8590-5de66a52d566.gif)

It's also worth noting that the ones that are actually picked, the real values, are my most recently used emoji. The ones it's showing are emojis I almost never use, which is what tipped me off to it being broken even before I noticed that I was sending people the wrong things. So whatever key it's using for tracking that appears to be right, as well as whatever it puts in the clipboard. Just not the display inside the picker itself, which baffles me 😅 (that looked like XD when I picked it 😛)

**Comment by maoschanz** [comment]
>maybe there's some way this makes sense to you that could explain what I'm seeing...

i don't know how it could reproduced but maybe i know what is happening. I think the emojis that are "remembered" as the recent ones are somehow corrupted. What's the result of 

    dconf read /org/gnome/shell/extensions/emoji-selector/recently-used

?

**Comment by psycotica0** [comment]
When I run that I appear to get the true emojis.
So it matches what we paste, not what it shows.

Is that what you expected?

**Comment by maoschanz** [comment]
yes and i'd like to see the result so i could know if its size is right

**Comment by psycotica0** [comment]
Oh shoot, sorry. Here you go!

```
$ dconf read /org/gnome/shell/extensions/emoji-selector/recently-used
['😛', '😅', '🤷', '👍', '😄', '😜', '🤞', '👅', '™', '🤘', '😒']
```

**Comment by maoschanz** [comment]
This time it's not what i expected at all 😓

it's really weird because all the code seems to work as intended, yet it doesn't

my only idea left would be a problem from GNOME Shell: for example if you paste the emoji in the overview's "search" field, is it the "true" emoji or the displayed-in-the-button one?

**Comment by psycotica0** [comment]
Ooh, good call! No. If I paste it back into the picker's search bar, it's still wrong. The same is true of the overview's search field, and what's even stranger is when I paste an emoji in the search there it lists "face with tongue stuck out `U+1F61B`, but shows the wrong face (😜)

**Comment by psycotica0** [comment]
That was kind of unclear. What I'm saying is that other places in Gnome are busted in the same way. So it's not your app! But I'm even more confused, honestly...

**Comment by maoschanz** [comment]
yes i'm confused too, and i don't know how this part works at all, so i can't help you fixing it

**Comment by psycotica0** [comment]
Yup. Thanks very much for helping me debug this! I'm going to close this out.
