### ISSUE TITLE
Contrast too low on text description

### ISSUE THREAD

**Issue by edent** [maoschanz/emoji-selector-for-gnome#154]
# System

- OS: Pop OS / Ubuntu
- Your version of the extension (visible in the "about" tab of the preferences window): v20
- Your version of GNOME Shell: 3.38.5 (Wayland)
- Most recent GNOME Shell version that is supposed to work ([visible here](https://extensions.gnome.org/extension/1162/emoji-selector/) in the dropdown): 3.38
- Is the extension supposed to work with your version of GNOME Shell [y/n]: y

# Description of the bug
Contrast between text and background is too low - I can't read what it says

![Screenshot from 2021-06-30 11-40-51](https://user-images.githubusercontent.com/837136/123947441-4b820280-d998-11eb-9af1-5b8de0cd3359.png)

Is your bug already reported? [y/n]: n But it might be related to https://github.com/maoschanz/emoji-selector-for-gnome/issues/113 as I'm using the POP OS Dark Theme

## To Reproduce

Steps to reproduce the bug:

1. Install on Pop OS using the dark theme
2. Try to read the text

## Expected behavior

Background colour should have a suitable contrast to the text.

**Comment by maoschanz** [comment]
sorry but that's a problem for whoever writes PopOS themes: tell them that an opened submenu should be readable even if its item is insensitive

meanwhile you can use the default theme, it works fine.
