### ISSUE TITLE
[Feature request] Shortcut key to open, enter to insert.

### ISSUE THREAD

**Issue by b-hayes** [maoschanz/emoji-selector-for-gnome#162]
Would be great if I could hit a key combo to bring up the emoji picker.
It already does go back to the last active window if I search for an icon and hit enter, however having, 
to use the mouse and then hit ctrl v afterwards is pretty inconvenient.

Im used to the windows emoji picker where my hands don't have to leave the keyboard and pressing enter just inserts the text so I don't have to paste it.

**Comment by maoschanz** [comment]
already asked several times, and far too complex to do

**Comment by b-hayes** [comment]
ah dang. I made a global shortcut to activate the current instance of another application with a bash script. Do you think I could modify this to make it work?

```
#!/usr/bin/env bash
if ! command -v xdotool; then
    echo "We need to install xdotool for this to work..."
    sudo apt install -y xdotool

fi

#Find the terminal window and activate or minimize it.
GNOME=`xdotool search --onlyvisible --class gnome-terminal`
ACTIVE=`xdotool getwindowfocus`

if [ "$GNOME" == "" ]; then
    gnome-terminal&
    exit 0
fi

if [ $GNOME == $ACTIVE ]; then
    #its already active so minimize it
    xdotool windowminimize $GNOME
    exit 0
fi

#activate the existing window.
xdotool windowactivate $GNOME
```

**Comment by maoschanz** [comment]
sorry i use Wayland so i've no idea how to do anything with "xdotool"

if the "class name" is what GNOME Shell calls a wmclass, then i guess the correct one will be named "Gnome-shell"? no idea what you want to do with it though

the simplest way to insert the emoji in the active window would be to go to the extension source code on your machine (~/.local share gnome-shell extensions emoji-selector), search for the method named `replaceClipboardAndClose`, and after `Clipboard.set_text` you call a script doing something like

- sleep 0.5 second so the popover has the time to close itself
- paste the emoji, with `xdotool type "$(xclip -o -selection clipboard)"` according to a quick google search

i don't remember how to call a sh commant from an extension but it probably corresponds to `Util.spawn(['array', 'of', 'strings']);`

**Comment by Queatz** [comment]
I wonder if it's possible to just have an option to trigger a system paste after the emoji window is unfocused
