### ISSUE TITLE
Can't set a hotkey (<Super> .)

### ISSUE THREAD

**Issue by ShadowOfPripyat** [maoschanz/emoji-selector-for-gnome#163]
# System

- OS: **Ubuntu 20.04.3 LTS x86_64**
- Your version of the extension (visible in the "about" tab of the preferences window): **v20**
- Your version of GNOME Shell: **3.36.8**
- Most recent GNOME Shell version that is supposed to work ([visible here](https://extensions.gnome.org/extension/1162/emoji-selector/) in the dropdown): **3.38**
- Is the extension supposed to work with your version of GNOME Shell [y/n]: **YES**

# Description of the bug

Is your bug already reported? [y/n]: **NO**

I want to set the same hotkey as in Windows 10 (<kbd>Win</kbd>+<kbd>.</kbd>), but i don't find the <kbd>.</kbd> key name in the provided list. I tried all ways to set that and it was impossible. **Please help**

## To Reproduce

Steps to reproduce the bug:

1. ... -I don't understand this point.
2. ...
3. ...

## Expected behavior

I kinda expected a solution to set the hotkey without having to see the list, or at least Just set my desired keybind and make it work idk.

**Comment by maoschanz** [comment]
>Is your bug already reported? [y/n]: NO

#53 #50 #128 #130 etc.

the name of the <kbd>.</kbd> key is `period`
