### ISSUE TITLE
Alternative modifier keys don't work

### ISSUE THREAD

**Issue by theCalcaholic** [maoschanz/emoji-selector-for-gnome#169]
# System

- OS: Ubuntu 20.04
- Your version of the extension: v20
- Your version of GNOME Shell: 3.36.8
- Most recent GNOME Shell version that is supposed to work ([visible here](https://extensions.gnome.org/extension/1162/emoji-selector/) in the dropdown): 3.38
- Is the extension supposed to work with your version of GNOME Shell [y/n]: y

# Description of the bug

Is your bug already reported? [y/n]: n

When using a different modifier key in the keyboard shortcut (i.e. other than `<Super>`) it will be ignored, meaning the shortcut will work as if the modifier wasn't there (e.g. if setting the shortcut to `<Shift_L>e` the emoji picker will open when pressing just e, but not when pressing Left Shift + e).

## To Reproduce

Steps to reproduce the bug:

1. Install the emoji selector extension
2. Set the keyboard shortcut in the extension settings to something like `<Control_L>e` or `<Shift_L>e`.
3. Attempt to open the emoji picker via shortcut

## Expected behavior

When pressing the configured shortcut, the emoji picker should open. It should not open on any other key combinations.

**Comment by maoschanz** [comment]
What makes you think these values should be recognized by the Mutter window manager? I don't know where the doc is located, but if i remember correctly, the valid ones are Ctrl, Primary, Hyper, Super, Meta, Shift, and something for the lock key. And of course you want to avoid shortcuts related to only ctrl or/and shift because those are used by applications themselves

**Comment by markcellus** [comment]
@maoschanz same thing just happened to me 😄

> What makes you think these values should be recognized by the Mutter window manager?

On Ubuntu, when clicking the "?" next to the shortcuts field, it shows a "List of valid key names" link that links to https://github.com/GNOME/gtk/blob/main/gdk/keynames.txt. That page lists `Control_L`, `Shift_L`, etc like @theCalcaholic mentioned. If that link shouldn't be used, it may be good to just remove it or update the reference to a more reliable set of key names.

**Comment by maoschanz** [comment]
oh my bad, i now understand the source of the confusion: this list is valid, but it's for the keys themselves, for example it's not `<Super>.` as you may think instinctively, but `<Super>period` instead like in the list

concerning the modifiers themselves, i still don't know where they're documented, but anyway shift+[random key] will just type the uppercase version of that random key, so it's not valid: a better attempt would be super+shift+that key, or ctrl+shift+that key

but when i'll have a computer to resume development i want to use the gtk4 dialog to ask for a key combination like they do in the system settings
