### ISSUE TITLE
Include U+20BF (Bitcoin Sign)

### ISSUE THREAD

**Issue by GraoMelo** [maoschanz/emoji-selector-for-gnome#175]
Dear developers,

could you add currency symbols:

Unicode: 

![btc-crrnc](https://user-images.githubusercontent.com/60477737/188610776-9cdd82ec-c007-41d0-a03f-01d6ea7980b6.png)

### Bitcoin Sign

| Name | Number |
| ------ | ------ |
| Number Unicode | U+20BF |
| ------ | ------ |
| HTML Code | : '&#8383'; |
| ------ | ------ |
| CSS code: | '\20BF' | 

<p>Unicode version 10: https://www.unicode.org/charts/PDF/Unicode-10.0/U100-20A0.pdf
<p>General information: https://util.unicode.org/UnicodeJsps/character.jsp?a=20BF
<p>Technical information: https://www.unicode.org/L2/L2015/15229-bitcoin-sign.pdf

**Comment by maoschanz** [comment]
the emojis are these characters: https://unicode.org/emoji/charts-14.0/full-emoji-list.html and other unicode symbols are out of scope

the extension is sadly not up to date with the standard yet, but there is fortunately no b*tcoin symbol in the standard
