### ISSUE TITLE
Update to Gnome 43.0

### ISSUE THREAD

**Issue by henriiquecampos** [maoschanz/emoji-selector-for-gnome#177]
Hello! I love this extension.

Recently my distro, Solus, updated to Gnome 43.0 and the extension doesn't support this version.

Any ETA for an update? Is there anyway I can help update it?

**Comment by eugenioperea** [comment]
Hi, is there a way to force Ubuntu to recognize the new version? I never imagined it would be the case, but Emoji Selector is my most used extension! : )

**Comment by henriiquecampos** [comment]
Thanks a lot @53R3n17Y-serenity ! I used the edit metadata.json approach and it worked!

**Comment by eugenioperea** [comment]
Awesome! I also used the metadata.json method and it worked perfectly.

**Comment by maoschanz** [comment]
i still have to release it on the gnome website, i'll do it this evening

**Comment by AlexWayfer** [comment]
> i still have to release it on the gnome website, i'll do it this evening

Great, thanks.

**Comment by Rmano** [comment]
Hi! It seems it's still at gnome 42:

![image](https://user-images.githubusercontent.com/6414907/201766422-2d362182-ddce-489d-b88f-61f9bee28839.png)

Thanks for the extension!

**Comment by maoschanz** [comment]
the update has been approved  🥳
