### ISSUE TITLE
put selected emoji to "middle-click-clipboard"

### ISSUE THREAD

**Issue by githubeing** [maoschanz/emoji-selector-for-gnome#55]
Not sure if you know that: Ubuntu has two different clipboards: one is ctrl+c/ctrl+v, the other is: when you select a text, it gets copied to 2nd clipboard, when you middle click your mouse, it gets pasted. Your extension only uses the first clipboard. Is it possible to also use the second one? I know you don't know how to type emojis directly into active focused input, but currently after I've selected an emoji I have to right click -> paste from context menu and it'd be great if I could simply paste it with just a middle click!

**Comment by maoschanz** [comment]
Not being able to paste from the keyboard, from a touchscreen, or from a touchpad: it's a bad idea.

And [according to the doc it's not possible too](https://www.roojs.org/seed/gir-1.2-gtk-3.0/seed/St.Clipboard.html)

**Comment by maoschanz** [comment]
Overwriting both clipboards ? idk, i'm not sure all users would like it, I'm glad the technical limitations of the St API helps me keeping things simple.

**Comment by githubeing** [comment]
For the user, the real simplicity is minimum usage effort, not minimum API involved (the latter is simplicity for the developer though 😉). To open the context menu and selecting the "paste" item EACH TIME 😠 is not a simple thing, IMO. That's why GNOME developers have created the middle click paste -- that helped them keeping usage simple! 🤷 If not so, then I don't understand at all: why have they bothered developing the middle click paste feature? 🤔

**Comment by githubeing** [comment]
> Not being able to paste ... from a touchpad

BTW, not sure if exactly _your_ touchpad supports this, but _my_ sure does. Middle click is activated by tapping with three fingers at same time. I use this feature all the time. Another way to activate middle click from my touchpad is clicking left and right touchpad buttons at the same time. The developers of touchpad driver know how important the middle click is and how often it is used, that's why they've bothered developing even _two_ different ways of activating it. They didn't think this'll make things complicated, because they knew how important the usage simplicity is. IMO

**Comment by amivaleo** [comment]
> Overwriting both clipboards ?

Please DON'T!
Use the middle-click-clipboard only, please.

**Comment by githubeing** [comment]
> > Overwriting both clipboards ?
> 
> Please DON'T!
> Use the middle-click-clipboard only, please.

Maybe, this should be a matter of preference (option)? The bad news is that our thoughts about this will never become true, because (as @maoschanz have stated) the GNOME extensions API doesn't yet allow using middle-click-clipboard. 😭

**Comment by amivaleo** [comment]
The fact is: I use 'Clipboard Indicator' extension from Tudmotu. That's part of my workflow (and I'm already a bit mad at the fact I can't increase the history size above 50 items...).
I do use whatsapp web too and some emojis. I don't want them to appear in that clipboard... :(

Anyway, @maoschanz: why do you use some custom-circular buttons for the emoji-categories instead of using the default one (like the power-button or the settings-button at the bottom of the user menu on the far right of the top bar)  that follow the shell theme? :3

**Comment by amivaleo** [comment]
> i'm not sure what you mean, it's using the "'system-menu-action'" style class, which isn't defined by my code, the only custom thing i do is the blue color when the category is opened

Those buttons do not behave like the ones in the user-menu. 🤔
For example: if you hover on any of the emoji-categories buttons, the border disappears.
![schermata da 2018-12-10 11-35-05](https://user-images.githubusercontent.com/24316547/49727174-e8acac80-fc6f-11e8-9e36-4596084cd369.png)

The buttons in the user-menu get a grey background instead.
![schermata da 2018-12-10 11-34-37](https://user-images.githubusercontent.com/24316547/49727184-ed716080-fc6f-11e8-8693-a08b78380872.png)

Also: if you click on a button in the user-menu without releasing the click, you can see that the button background becomes light-blue. This color depends on the shell-theme in use.

**Comment by maoschanz** [comment]
oh, pseudo-classes ? open an issue for this, it might be a simple line i forgot like `track_hover: true` or this kind of thing, i'll see that later

**Comment by amivaleo** [comment]
> oh, pseudo-classes ?

Don't know what they are... :(

> open an issue for this, it might be a simple line i forgot like `track_hover: true` or this kind of thing, i'll see that later

Ok. 🤨

**Comment by maoschanz** [comment]
i'm not an expert in CSS but iirc there are classes (`.something{ ... }`) and pseudo-classes (`.something:hover{ ... }`, `.something:active{ ... }`, etc.)

**Comment by amivaleo** [comment]
> i'm not an expert in CSS but iirc there are classes (`.something{ ... }`) and pseudo-classes (`.something:hover{ ... }`, `.something:active{ ... }`, etc.)

Oh yeah! Those ones. :)
I'm not an expert either. I learned something by myself and I don't know how to call things. ^_^
