### ISSUE TITLE
Unable to paste emojis in Chrome

### ISSUE THREAD

**Issue by EgidioCaprino** [maoschanz/emoji-selector-for-gnome#60]
Hi all :wave:

I'm using this Gnome extension and I love it, but for some reason I'm not able to paste emojis into Chrome anymore, in the majority of websites.

Do you know what a possible cause could be?

**Comment by maoschanz** [comment]
this extension uses the regular clipboard so if something is broken it may be chrome

**Comment by EgidioCaprino** [comment]
Oh yes, the problem is surely with Chrome. I was wondering if you have any idea about what could cause that.

**Comment by maoschanz** [comment]
not really, maybe wayland ?

**Comment by EgidioCaprino** [comment]
Don't think so. For some site, like Gmail, it works fine. Maybe it is related to fonts?

**Comment by maoschanz** [comment]
if fonts don't support emojis, i think some white squares will be pasted

**Comment by EgidioCaprino** [comment]
That's not the case. Simply nothing happens when pasting the selected emoji

**Comment by maoschanz** [comment]
weird... is the emoji really copied to the clipboard?
