### ISSUE TITLE
Support for ES6 classes *while still being retro-compatible if possible*

### ISSUE THREAD

**Issue by ronjouch** [maoschanz/emoji-selector-for-gnome#63]
`journalctl` indicates it errors with:

```
gnome-shell[19665]: Extension "emoji-selector@maestroschan.fr" had error: TypeError: this._construct is not a function
```

[Googling a bit](https://www.google.com/search?q="TypeError%3A+this._construct+is+not+a+function") and stumbling upon https://github.com/micheleg/dash-to-dock/issues/877 , it looks like 3.32 no longer likes using `Lang.Class`, and extensions should be ported to ES6 classes. As usual, marvelous backward compatibility & documentation, GNOME 😕.

I'm using the latest version available on extensions.gnome.org.

**Comment by maoschanz** [comment]
ok, that's embarassing, I'll fix my extensions (or, to be exact: i'll break them for anyone using 3.30 or before) when Debian Sid will be updated to 3.32

**Comment by AlexWayfer** [comment]
> i'll break them for anyone using 3.30 or before

I think, there will be available current versions for ≤ 3.30.

> when Debian Sid will be updated to 3.32

Ouch…

**Comment by kirbyfan64** [comment]
I've gotten this to work locally, will be submitted soon pending a rebase onto the most recent master commits.

**Comment by maoschanz** [comment]
I want to warn you that a few hours ago i was still refactoring the code, and i haven't finished, so there is crap everywhere in the code

**Comment by kirbyfan64** [comment]
Haha nah, I partly just did it so I could have it back (IRC is a dark world without emoji).

**Comment by maoschanz** [comment]
@kirbyfan64 i added 3.26 to 3.30 support, could you confirm that my modifications are not breaking the extension on 3.32 ?

**Comment by ronjouch** [comment]
> i added 3.26 to 3.30 support, could you confirm that my modifications are not breaking the extension on 3.32 ?

@maoschanz I confirm master @ 76ed815c58a6176964e24af5693548e73d476b77 works 👍 for me in [Shell 3.32.0+20+g05e55cee2-1 from Arch](https://www.archlinux.org/packages/extra/x86_64/gnome-shell/). Thanks everyone 🙂.
