### ISSUE TITLE
categories not built

### ISSUE THREAD

**Issue by jjgalvez** [maoschanz/emoji-selector-for-gnome#66]
selecting a type of emoji does not bring up the list of emoji 
![Screenshot from 2019-03-25 20-54-25](https://user-images.githubusercontent.com/5430012/54963852-a5392e00-4f40-11e9-8726-17d79985821c.png)

clicking the smiles button should bring up a list of emoji

**Comment by maoschanz** [comment]
When/where did you download and install this ? If it's the version from yesterday on github it's normal, otherwise it's not

**Comment by jjgalvez** [comment]
via the AUR, yes it is the version from yesturday's github commit. Is this going to be the expected behavior going forward, because it does make finding the right emoji difficult. Or is this expected to be temporary as the gnome-shell 3.32 changes all get sorted out?

**Comment by maoschanz** [comment]
I'm changing a lot of things in the code so there might be temporary regressions, but it's not linked to 3.32

**Comment by jjgalvez** [comment]
Sounds good, and thanks for the hard work, it's a great extension




Get Outlook for Android







On Tue, Mar 26, 2019 at 12:17 PM -0400, "Romain F. T." <notifications@github.com> wrote:












I'm changing a lot of things in the code so there might be temporary regressions, but it's not linked to 3.32
