### ISSUE TITLE
no emoji, just blank tiles

### ISSUE THREAD

**Issue by psykotik1** [maoschanz/emoji-selector-for-gnome#67]
extension works for the most part, aside from emoji not showing. :)
when i mouse over an emoji the name shows in the window though.

arch linux gnome 3.32

**Comment by maoschanz** [comment]
screenshot ?

**Comment by psykotik1** [comment]
![image](https://user-images.githubusercontent.com/11342059/55291222-d6cb5280-53a1-11e9-9d36-97d1cb757978.png)

**Comment by maoschanz** [comment]
4 possibilities:

- no adequate font installed
- the theme forces a font without emojis
- the size is too small, you can change it in the extension's settings
- a bug (i don't have 3.32 so i can't test), which should be visible in the output of `sudo journalctl -f /usr/bin/gnome-shell`

**Comment by psykotik1** [comment]
here is the output of journalctl: after disabling/enabling the extension, then clicking on the icon

Mar 31 22:27:01 zephyr gnome-shell[875]: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
Mar 31 22:27:01 zephyr gnome-shell[875]: cr_declaration_parse_list_from_buf: assertion 'parser' failed
Mar 31 22:27:01 zephyr gnome-shell[875]: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
Mar 31 22:27:01 zephyr gnome-shell[875]: cr_declaration_parse_list_from_buf: assertion 'parser' failed
Mar 31 22:27:03 zephyr gnome-shell[875]: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
Mar 31 22:27:03 zephyr gnome-shell[875]: cr_declaration_parse_list_from_buf: assertion 'parser' failed

**Comment by psykotik1** [comment]
i think you were right, i was using a theme with a custom font, changing that made the emoji appear, thank you for your quick response.

**Comment by timtorChen** [comment]
I got the same problem.

-  Error log
```
$sudo journalctl -f /usr/bin/gnome-shell
 1月 02 22:26:07 timtor-hp gnome-shell[2018]: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
 1月 02 22:26:07 timtor-hp gnome-shell[2018]: cr_declaration_parse_list_from_buf: assertion 'parser' failed
 1月 02 22:26:07 timtor-hp gnome-shell[2018]: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
 1月 02 22:26:07 timtor-hp gnome-shell[2018]: cr_declaration_parse_list_from_buf: assertion 'parser' failed
 1月 02 22:26:08 timtor-hp gnome-shell[2018]: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
 1月 02 22:26:08 timtor-hp gnome-shell[2018]: cr_declaration_parse_list_from_buf: assertion 'parser' failed
 1月 02 22:26:08 timtor-hp gnome-shell[2018]: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
 1月 02 22:26:08 timtor-hp gnome-shell[2018]: cr_declaration_parse_list_from_buf: assertion 'parser' failed
 1月 02 22:26:13 timtor-hp gnome-shell[2018]: cr_parser_new_from_buf: assertion 'a_buf && a_len' failed
 1月 02 22:26:13 timtor-hp gnome-shell[2018]: cr_declaration_parse_list_from_buf: assertion 'parser' failed
```

- System configs
Emoji related font installed: `twemoji-color-font` and `fonts-noto-color-emoji`
Theme: Yaru
Linux distributions: Ubuntu 19.10
Gnome version: 3.34.1
