### ISSUE TITLE
Searched emojis are black.

### ISSUE THREAD

**Issue by Philipp0205** [maoschanz/emoji-selector-for-gnome#71]
Hello,
I installed the extension and noticed this:

![image](https://user-images.githubusercontent.com/36603238/57181341-a2602000-6e92-11e9-8148-28b253f31cfb.png)

Recent emojis and searched emojis appear black. Any way to get rid of this?

**Comment by maoschanz** [comment]
have you installed a font supporting color emojis?

**Comment by Philipp0205** [comment]
Yep I have! After several restarts it works now... let's see.

**Comment by axelitus** [comment]
I'm having the same issue although I have the fonts-noto-color-emoji font installed...
![image](https://user-images.githubusercontent.com/732441/60769622-bcd39700-a097-11e9-8ce4-056efa1879c8.png)

Have tried uninstalling and re-installing the extension several times and always with the same result.

**Comment by maoschanz** [comment]
ah, i think i understood the issue...

you've just enabled the setting "use a dark font", which exists for people without color emojis using a light theme

**Comment by axelitus** [comment]
@maoschanz that was it! Thank you very much. I disabled that option, disabled the extension and re-enabled it again and now it's working great!
![image](https://user-images.githubusercontent.com/732441/60773036-6761af00-a0c4-11e9-89c9-cc4d69573174.png)

**Comment by maoschanz** [comment]
>you've probably enabled the setting "use a dark font", which exists for people without color emojis using a light theme

This option has been removed entirely in the version 17 (i assume everyone has a font with color emojis in 2020)
