### ISSUE TITLE
Present but not installed?

### ISSUE THREAD

**Issue by tsbertalan** [maoschanz/emoji-selector-for-gnome#73]
Recently, I've noticed that Ctrl+. brings up an "Emojis & People" popup in what looks to be Gnome applications (noticed first in Nautiluis, then in the Settings app, then in Gnome Tweaks). However, in "Extensions" in Gnome Tweaks, I don't have this installed. Do you know where this is coming from? Is it a feature of Ubuntu now?

I'm on Ubuntu 18.04.2 LTS, with 4.15.0-47-generic. Those listed extensions are "Multi monitors add-on", "Ubuntu appindicators", and "Ubuntu dock", though only the first is turned on in Gnome Tweaks.

**Comment by maoschanz** [comment]
It's a standard feature from GTK.

GNOME Shell extensions have nothing to do with applications.
