### ISSUE TITLE
The extension freezes when selecting emoji

### ISSUE THREAD

**Issue by m93a** [maoschanz/emoji-selector-for-gnome#76]
I'm on Ubuntu 18.04.1. The Emoji Selector extension used to work just fine unitl recently. Now the category icons disappeared (#75) and sometimes (quite often actually) when I select an emoji, everything freezes for ~20 seconds. I can move my mouse but can't interact with any other application. After that interval, the extension loses focus and I'm able to interact with other applications and paste the emoji I selected.

A footage of that bug can be seen here: https://youtu.be/JmwitZIoeXo

**Comment by maoschanz** [comment]
as you can guess, a footage where nothing is visible is not very useful. Concerning icons, use the same solution i give in #75 (use a recent icon theme), concerning the freeze:

- disable the other extensions
- `sudo journalctl -f /usr/bin/gnome-shell`
- then reproduce the bug
- and paste the logs here
