### ISSUE TITLE
What do you think about adding support for accented characters?

### ISSUE THREAD

**Issue by snydox** [maoschanz/emoji-selector-for-gnome#77]
It would be nice to have an easy way to type accented characters a la the macOS. In macOS if you long press the letter a, you get a popup menu with all the combinations for that vowel.

Source: https://support.apple.com/en-ca/HT201586

Maybe your extension could include these characters as well, rather than using the compose key.

**Comment by maoschanz** [comment]
in my opinion that's out of the scope of this extension
