### ISSUE TITLE
Why is Brunei listed twice in emojisKeywords?

### ISSUE THREAD

**Issue by ChildishGiant** [maoschanz/emoji-selector-for-gnome#78]
https://github.com/maoschanz/emoji-selector-for-gnome/blob/f35f288d6db57f724e85c6eb7a2da2789655eaf1/emoji-selector%40maestroschan.fr/emojisKeywords.js#L1505-L1506

I'm working on a PR and noticed that Brunei is listed twice. The linked page only shows it once.
![image](https://user-images.githubusercontent.com/13716824/59807248-15acdc80-92ef-11e9-856b-9e672a2d0616.png)

**Comment by maoschanz** [comment]
the data is outdated because building it manually is long and boring: sometimes a line is forgotten

someone else noticed it, it has been fixed by #87
