### ISSUE TITLE
Exact matches not first result

### ISSUE THREAD

**Issue by ChildishGiant** [maoschanz/emoji-selector-for-gnome#79]
EG: If I want the 👀 emoji which is called "eyes" I search for "eyes" but it doesn't come up in the search results as they are limited and exact matches aren't prioritised

![image](https://user-images.githubusercontent.com/13716824/59957043-9c4af080-948c-11e9-8552-18c19c61a9bd.png)

**Comment by pornismuybae** [comment]
Surely this is worse now? :eyes: 
 ![image](https://user-images.githubusercontent.com/48782002/80434573-04aaff80-88f2-11ea-8384-93306d2e5709.png)

**Comment by maoschanz** [comment]
>now

>screenshot of the old version

if you're here because some notification told you there was a new version, it has not been installed on your system because of #100
