### ISSUE TITLE
Symbols for categories are blank (white on white) with certain gnome shell themes

### ISSUE THREAD

**Issue by zeparu** [maoschanz/emoji-selector-for-gnome#84]
![grafik](https://user-images.githubusercontent.com/21054889/61998007-cb670a00-b0a9-11e9-96e8-a4b2bc5df9cf.png)
im using the arc gnome shell theme, and the text for search, and the emojis show up well enough, but the icons for the categories arent visible because i assume they still use the white icon, when the popup is also white
(also the icons are bugged, but thats just a gnome shell bug that i sometimes get after fullscreen wine/dxvk games)

**Comment by frederik-elwert** [comment]
I noticed probably the same issue under Ubuntu 18.04 with the default Ambiance theme:

![emoji_categories_bug](https://user-images.githubusercontent.com/3049661/63003643-e6db5e80-be78-11e9-957e-ae015d0260cc.png)

**Comment by nazrhyn** [comment]
I've been experiencing the same thing using these themes:   
![image](https://user-images.githubusercontent.com/1672405/70346211-c53d2300-182b-11ea-8057-f353ab0d2886.png)

When I switched back to Ambiance, here's what I see:   
![image](https://user-images.githubusercontent.com/1672405/70346257-ebfb5980-182b-11ea-8e95-c15eaf7c79c2.png)   
(However, I had to do an <kbd>ALT</kbd>+<kbd>F2</kbd>, <kbd>r</kbd> to get them to show after changing themes.)

However, when I switched _back_ to my theme, even after <kbd>ALT</kbd>+<kbd>F2</kbd>, <kbd>r</kbd>, it looked fine :thinking::
![image](https://user-images.githubusercontent.com/1672405/70346524-7f348f00-182c-11ea-8543-c4c37da3cb86.png)

So, I think I'm saying I _don't_ have the same problem now? I'm not sure if it will come back later.

**Comment by fnune** [comment]
On my default theme on Gnome it looks like this:

![image](https://user-images.githubusercontent.com/16181067/77710675-fdc95e00-6fce-11ea-88d3-5a692e71f7c2.png)

**Comment by maoschanz** [comment]
reminder that you're using an extension that doesn't support GNOME 3.36 yet
