### ISSUE TITLE
Are there emoji missing? (Example: the English flag 🏴󠁧󠁢󠁥󠁮󠁧󠁿)

### ISSUE THREAD

**Issue by echosa** [maoschanz/emoji-selector-for-gnome#86]
I just installed this extension, and it's awesome! However, it seems to be missing some emoji. For instance, the flag for England (🏴󠁧󠁢󠁥󠁮󠁧󠁿) isn't there. I typed "eng" to search and manually looked for it in the flag area. I'm not sure what, if any, other emoji are missing.

**Comment by maoschanz** [comment]
the extension uses unicode 10 while the newest standard is 12.1

**Comment by maoschanz** [comment]
fixed (i added unicode 11) but notice that on Ubuntu 18.04 LTS, the 4 last emojis of the "flags" category are not correctly rendered (they are England, Wales, Scotland, Texas), i think it's a font issue with older distros
