### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by hailwood** [maoschanz/emoji-selector-for-gnome#89]
Hey @maoschanz,

Love the extension, it's probably my most used one!

Quick question, can you please add a changelog? :) I like to know what updates there are when installing them!

Cheers

**Comment by maoschanz** [comment]
i don't update this one a lot, i'm not even sure when i did the last release, so i don't know what happened since then

i guess the last update was mostly pointless code refactoring and fixing compatibility with newer GNOME Shell versions

**Comment by maoschanz** [comment]
I've not forgotten this time! https://github.com/maoschanz/emoji-selector-for-gnome/releases/tag/17
