### ISSUE TITLE
[Gnome 3.36] The CSS class for category icons doesn't exist anymore

### ISSUE THREAD

**Issue by ronjouch** [maoschanz/emoji-selector-for-gnome#92]
![screenshot_emojiselector-gnome336_2020-03-08-09:00:01](https://user-images.githubusercontent.com/522085/76163335-8c0e9a80-611b-11ea-9d81-003c2e12709b.png)

(yup, 3.36 isn't "officially released", but it's tagged in Git and [released to Arch users](https://www.reddit.com/r/archlinux/comments/ffbef4/gnome_336_has_landed_in_extra/)).

**Comment by maoschanz** [comment]
Using symbolic icons is consistent with... GNOME design guidelines. I mean, what is supposed to be the alternative? Pick one random existing emoji in each category and use its character in the button, so people without a compatible font wouldn't even get an usable UI? No, i will not change this design decision.

Then yes the buttons use the CSS class for the cool power/lock buttons everyone enjoyed. In 3.36 they decided to use an ugly submenu so i have to rewrite some CSS myself

**Comment by ronjouch** [comment]
> Using symbolic icons is consistent with... GNOME design guidelines. I mean, what is supposed to be the alternative? Pick one random existing emoji in each category and use its character in the button, so people without a fully compatible font wouldn't even get an usable UI? No, sorry i will not change this design decision

@maoschanz oh, you're right, now that I think about it, that was already the case before 😄. I just got surprised by the icon size, and incorrectly considered using symbolic icons was a regression. The rename you did is correct: forget about the symbolic thing, the only bug here is the size. Thanks for the fast feedback.

---

A personal aside: after years of occasional issue reporting here, I noticed you're frequently defensive in your replies, which makes the communication irritating for everyone. I can understand it and am not lecturing you, as I'm also sometimes guilty of it, once in a while replying grouchily to unclear/nonsensical issues for the software I'm maintaining.

Contrast the abrasiveness of your answer with simply pointing out the error: *"Symbolic icons were already used in 3.34, this is not new, the symbolic icons must simply have surprised you because of the size bug"*.

Relax. Step back from the keyboard and try to see the *good* in the user request. Some user requests are unclear, some (like this one) are incorrect. It doesn't mean they are an aggression though. Assume goodwill. Don't assume intent. Stop blaming. It will feel better.

**Comment by maoschanz** [comment]
yes sorry i should hide it but i'm very pissed with anything related to extensions, it's not really the users, it's because it's such a pain to maintain, every GS version is regressing for no valid reason, retro-compatibility is non-existent, etc.

Then people always report things literally the day of the Arch release. It's like yall expect me to use Arch? Lol, never, my extension isn't broken, Arch is. But if extensions were maintainable i wouldn't mind 

Some of these extensions shouldn't even exist anymore, i would prefer to focus on my other apps (at least python has actual objects and doesn't uselessly changes its syntax at each update...)

**Comment by ronjouch** [comment]
> yes sorry i should hide it but i'm very pissed with anything related to extensions, it's not really the users, it's because it's such a pain to maintain, every GS version is regressing for no valid reason, retro-compatibility is non-existent, etc.
> 
> Some of these extensions shouldn't even exist anymore, i would prefer to focus on my other apps (at least python has actual objects and doesn't uselessly changes its syntax at each update...)

@maoschanz two things:

1. Thanks for admitting and explaining your frustration 👏👏👏. 100% agreed GS backwards compatibility & docs aren't great; I can relate it must be frustrating to build on top of that.
2. You do *not* have to hide things. *"Goddammit GS broke again, gah, when will they take compatibility seriously!@#$%"* is totally fine.

> Then people always report things literally the day of the Arch release. It's like yall expect me to use Arch? Lol, never, my extension isn't broken, Arch is. But if extensions were maintainable i wouldn't mind

Here I think you're taking things unnecessarily personally/defensively. There's nothing in this issue that says *"You, maintainer, suck, and your extension is broken"*. This issue only states a fact that there's a little regression under 3.36, without personal judgement. Or, to follow-up on the word "expect" that you use: I didn't expect you, the maintainer, to have fixed that before release, and I don't expect you to run Arch. No expressed expectation / blaming, I'm only trying to help by providing a little datapoint that you may address if/when you have the time for it 🙂. Bugs happen all the time!

Thanks again for taking the time to chat, and thanks for maintaining this helpful extension. Cheers 🙂.

**Comment by ronjouch** [comment]
Fix confirmed!

**Comment by ronjouch** [comment]
> i'm very pissed with anything related to extensions, it's not really the users, it's because it's such a pain to maintain, every GS version is regressing for no valid reason, retro-compatibility is non-existent, etc.

@maoschanz if this issue is still of interest to you, this year's online [GUADEC has a "GNOME Shell Extensions" session](https://events.gnome.org/event/16/) today Sunday July 26 at 18:00 UTC, which [according to Sri Ramkrishna](https://blogs.gnome.org/sri/2020/07/26/gnome-extensions-bof-1800-utc-july-26-2020/) includes this topic. Copy-pasting the blogpost linked above,

> We will be having a conversation around extensions and the future of how we will be handling them based on policy, community, and other important factors.
> 
> If you are an extensions writer, then I would urge you to join our BoF to help understand what we will be doing with extensions going forward and also provide feedback. We do not want to do this in a vacuum.
> 
> https://events.gnome.org/event/16/
> 
> Looking forward to hearing from the community. Some of things we will be talking about:
> 
> * Centralilzing the location of extensions to the GNOME gitlab (not necessarily develop your extensions there, but if you want it on e.g.o then it will need to pass QA tests)
> * Automatic QAing of extensions prior to release of gnome-shell.
> * Policies
> * Documentation
> * Community building
