### ISSUE TITLE
[Gnome 3.36] Enter key doesn't add emoji to clipboard

### ISSUE THREAD

**Issue by ronjouch** [maoschanz/emoji-selector-for-gnome#93]
An additional regression in 3.36, for when you find the time to look at it:

- Clicking an emoji works as expected: the emoji is added to the clipboard and the extension panel is closed...
- ... but the <kbd>Enter</kbd> key no longer works: say I use the arrows to highlight an emoji in the history, and press <kbd>Enter</kbd>, then nothing happens: emoji is not added to the clipboard and extension panel remains open.

Other extensions adding text to the clipboard on hitting <kbd>Enter</kbd> (e.g. Clipboard Indicator) **do** work, so this is not a Gnome Shell bug.

Running Gnome Shell 3.36.0 under Arch.

**Comment by Tyrben** [comment]
Same bug in Gnome 3.30. I've a Debian 10. This extension worked in November as I remember, since then… I have this bug.

**Comment by rawkode** [comment]
Yep. Came to report this :cry:

**Comment by ryzokuken** [comment]
@maoschanz any updates on this yet?

**Comment by ronjouch** [comment]
Give the maintainer a break. He knows about this bug, he flagged it as such. Maybe he doesn't have the time or will to fix it, or maybe he's not using 3.36 yet.

Please do one of:

1. Voting on the issue with a thumbs up
2. Submitting a PR
3. Waiting for a fix

, but stop polluting issues with "me too" comment, please. Thanks 🙂.

**Comment by ryzokuken** [comment]
@ronjouch I'm sorry, this was not my intent. I was literally just asking for the current status, and if they haven't started working on a patch, submit one instead.

**Comment by maoschanz** [comment]
i haven't started because i don't have 3.36 yet (it works fine on both 3.28 and 3.34, so i'm not even sure @Tyrben 's issue is the same one)

if you have an error log to provide i can try to fix it blindly, otherwise patches are welcome (as long as they don't break the extension on 3.28)

**Comment by maoschanz** [comment]
The issue was that some genius working on Clutter decided to rename most keyboard keys...

Until i release the new version, the numpad "return" key should still work
