### ISSUE TITLE
Enter does not work in GNOME 3.36

### ISSUE THREAD

**Issue by AlexWayfer** [maoschanz/emoji-selector-for-gnome#98]
Hello.

I can't select emoji via keyboard: I'm selecting one via `Tab` or Arrows and `Enter` does nothing. I have to use mouse for this.

**Comment by AlexWayfer** [comment]
Can you please describe when you close? Duplicate of what?

I found: #93. Strange that I didn't see it before posting while I check.

**Comment by maoschanz** [comment]
duplicate of #93, yes

it's already fixed, the new version of the extension with the fix will be released when it'll be ready
