### ISSUE TITLE
Enable Mac like search shortcut

### ISSUE THREAD

**Issue by Azer0s** [maoschanz/emoji-selector-for-gnome#99]
On Mac OS, the shortcut is `⌃+⌘+Space`, so naturally, I wanted to set the shortcut for the emoji selector to `<ctrl><alt><space>`. 

Unfortunately, this does nothing. Am I doing something wrong or is this just no supported yet?

I'm running Pop!_OS 19.10

**Comment by maoschanz** [comment]
<kbd>`<Ctrl>`</kbd><kbd>`<Alt>`</kbd><kbd>`space`</kbd>

**Comment by Azer0s** [comment]
@maoschanz Woah...that actually did the trick. Thanks!!
